// Markdown content negotiation for agents: requests with Accept: text/markdown
// on page routes get a Markdown rendition (generated by scripts/agentify.mjs);
// everything else falls through to the static assets (the SPA).
// Only runs on the routes listed in wrangler.jsonc `run_worker_first` —
// asset requests never invoke it.

function markdownPathFor(pathname) {
  if (pathname === "/") return "/md/index.md";
  if (pathname === "/progress") return "/md/progress.md";
  const m = pathname.match(/^\/lesson\/([\w-]+)\/?$/);
  return m ? `/md/lesson/${m[1]}.md` : null;
}

export default {
  async fetch(request, env) {
    const accept = request.headers.get("Accept") ?? "";
    if (request.method === "GET" && accept.includes("text/markdown")) {
      const url = new URL(request.url);
      const mdPath = markdownPathFor(url.pathname);
      if (mdPath) {
        const res = await env.ASSETS.fetch(new URL(mdPath, url.origin));
        if (res.ok) {
          return new Response(res.body, {
            headers: {
              "Content-Type": "text/markdown; charset=utf-8",
              "Vary": "Accept",
            },
          });
        }
      }
    }
    return env.ASSETS.fetch(request);
  },
};
